### ISSUE TITLE
pyjs_browser_runtime.js requires manual patching

### ISSUE THREAD

**Issue by trentfridey** [qutip/qutip-virtual-lab#1]
Until emscripten-forge/pyjs#44 is fixed, Webpack requires us to patch `pyjs_runtime_browser.js` before running the development server. This is annoying, but the fix is simple: after generating the runtime, do a find and replace on the two items:

1. Replace variables named `package` with `pkg` (or whatever, as long as it's not a reserved word)
2. Remove `import(import_str)` (find+replace with '')

**Comment by hodgestar** [comment]
Thoughts / questions:
- Let's add a build script that applies the necessary change.
- Is it possible to build and test the package in GitHub Actions?

**Comment by trentfridey** [comment]
I have added a script in 1e8c72e that should patch the pyjs runtime when running `yarn start:with_docker`. It's not great, but it should allow you to build the project. 

It should be possible to build and test the package in GitHub Actions, we just need to specify a runner with Node, Yarn, and Docker installed, and then have it run `yarn build:with_docker`
